name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      # https://github.com/microsoft/playwright/issues/7249
      - name: Get Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(bun -e 'console.log(require("playwright/package.json").version)')" >> $GITHUB_ENV

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: bunx playwright install chromium

      - name: Install Playwright OS dependencies
        run: bunx playwright install-deps chromium

      - run: bun test
        env:
          TEST_AUTH_BODY_URL: ${{ secrets.TEST_AUTH_BODY_URL }}
          TEST_LIVE_SEND_URL: ${{ secrets.TEST_LIVE_SEND_URL }}
          TEST_LOGIN_SYNC_TOKEN: ${{ secrets.TEST_LOGIN_SYNC_TOKEN }}
